env:
  es6: true
  node: true
  jest: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: true
  no-underscore-dangle:
    - error
    - allow: [_id]
      allowAfterThis: true
      allowAfterSuper: true
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  max-classes-per-file: off
  no-param-reassign: off
  import/prefer-default-export: off
